### ISSUE TITLE
Reuse existing docstring

### ISSUE THREAD

**Issue by marconetto** [heavenshell/vim-pydocstring#107]
If I execute the "Pydocstring" command on a python function that already has the docstring, but for instance, a new variable was added, this plugin seems to increate the docstring template for that function from scratch (keeping the existing one there). Is this the expected behaviour of the plugin? If yes, a nice feature would be to reuse the existing docstring and just add new content in the docstring that is required (e.g. new variable). Could also thing about removing a variable and removing the docstring component of that variable.

**Comment by heavenshell** [comment]
@marconetto 
Hi, Thanks for suggestion.

Yes, expected behavior.

![Kapture 2020-08-25 at 22 22 56](https://user-images.githubusercontent.com/56591/91179589-abc56980-e721-11ea-9c8e-4f52a15eaedf.gif)

Because generate docstring is simple.
```python
def | foo(arg1, arg2):
```
`|` is cursor, vim-pydocstring send `def foo(arg1, arg2): pass` to AST parser.
vim-pydocstring does not know docstring already exists or not.

But if `visual select` was on and it's includes docstring, AST parser know docstring is already exists and ignore to generate docstring.

> a nice feature would be to reuse the existing docstring and just add new content in the docstring that is required (e.g. new variable). 

Sorry currently I don't have any plan to do this.
I know it's convinent, but it too much complex.

Diffing old docstring and new docstring, compare it and add ore delete docstring param is hard.
See https://github.com/heavenshell/py-doq/issues/30 for why I don't do this.
